<?php
/**
 * blacklist-sync.php — Sync banned IPs + blocked agents to nginx blacklist files
 * Schedule: Every 15 minutes
 */
$args = [];
foreach ($argv as $arg) { if (preg_match('/^--([a-z_-]+)=(.+)$/', $arg, $m)) $args[$m[1]] = $m[2]; }
$run_id = (int)($args['run-id'] ?? 0);

echo "=== BackDraft Blacklist Sync ===\n";
echo "Started: " . date('Y-m-d H:i:s') . "\n\n";

try {
    $pdo = new PDO('mysql:host=127.0.0.1;port=3306;dbname=mcaster1_backdraft;charset=utf8mb4',
        'DUMMY_MARIADB_USER_SET_VIA_VAULT', 'DUMMY_MARIADB_PWD_SET_VIA_VAULT',
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
} catch (PDOException $e) { echo "FATAL: " . $e->getMessage() . "\n"; exit(1); }

// ── IP Blacklist ─────────────────────────────────────────────────────────
$banned = $pdo->query("SELECT ip_addr FROM backdraft_ip_reputation WHERE banned = 1")->fetchAll(PDO::FETCH_COLUMN);
echo "Banned IPs: " . count($banned) . "\n";

$ip_content = "# Auto-generated by BackDraft — " . date('Y-m-d H:i:s') . "\n";
$ip_content .= "# " . count($banned) . " banned IPs from backdraft_ip_reputation\n";
foreach ($banned as $ip) $ip_content .= "$ip 1;\n";

file_put_contents('/tmp/backdraft_ip_blacklist.conf', $ip_content);
exec('sudo cp /tmp/backdraft_ip_blacklist.conf /etc/nginx/blacklists/ip_blacklist.conf 2>&1', $out, $ret);
unlink('/tmp/backdraft_ip_blacklist.conf');
echo "IP blacklist write: " . ($ret === 0 ? "OK" : "FAILED ($ret)") . "\n";

// ── Agent Blacklist ──────────────────────────────────────────────────────
$agents = $pdo->query("
    SELECT DISTINCT pattern FROM (
        SELECT pattern FROM backdraft_agent_signatures WHERE disposition = 'block' AND active = 1
        UNION
        SELECT pattern FROM backdraft_bot_definitions WHERE disposition = 'block' AND active = 1
    ) combined ORDER BY pattern
")->fetchAll(PDO::FETCH_COLUMN);
echo "Blocked agents: " . count($agents) . "\n";

$bot_content = "# Auto-generated by BackDraft — " . date('Y-m-d H:i:s') . "\n";
foreach ($agents as $pattern) {
    if (strpos($pattern, '~*') !== 0) $pattern = "~*$pattern";
    $bot_content .= "$pattern 1;\n";
}

file_put_contents('/tmp/backdraft_bot_blacklist.conf', $bot_content);
exec('sudo cp /tmp/backdraft_bot_blacklist.conf /etc/nginx/blacklists/bot_blacklist.conf 2>&1', $out2, $ret2);
unlink('/tmp/backdraft_bot_blacklist.conf');
echo "Agent blacklist write: " . ($ret2 === 0 ? "OK" : "FAILED ($ret2)") . "\n";

// ── Test + Reload nginx ──────────────────────────────────────────────────
exec('sudo nginx -t 2>&1', $test_out, $test_ret);
if ($test_ret === 0) {
    exec('sudo nginx -s reload 2>&1');
    echo "nginx reloaded\n";
} else {
    echo "nginx test FAILED — not reloading\n";
    echo implode("\n", $test_out) . "\n";
}

// Update config timestamp
$pdo->prepare("UPDATE backdraft_config SET config_value = ? WHERE config_key = 'blacklist_last_sync'")
    ->execute([date('Y-m-d H:i:s')]);

echo "\nCompleted: " . date('Y-m-d H:i:s') . "\n";
