<?php

require_once __DIR__ . '/../web/app/inc/config.php';
/**
 * bot-definition-update.php — Download external bot lists, merge, generate nginx files
 * Replaces /etc/nginx/botupdates.sh with BackDraft-managed task
 * Schedule: Every 24 hours
 */
echo "=== BackDraft Bot Definition Update ===\n";
echo "Started: " . date('Y-m-d H:i:s') . "\n\n";

try {
    $pdo = new PDO('mysql:host=127.0.0.1;port=3306;dbname=mcaster1_backdraft;charset=utf8mb4',
        BD_DB_USER, BD_DB_PASS,
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
} catch (PDOException $e) { echo "FATAL: " . $e->getMessage() . "\n"; exit(1); }

// ── Download external bot lists ──────────────────────────────────────────
$sources = [
    'mitchellkrogza_bad' => 'https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/bad-user-agents.conf',
];

$external_bots = [];
foreach ($sources as $name => $url) {
    echo "Downloading {$name}...\n";
    $ctx = stream_context_create(['http' => ['timeout' => 15, 'user_agent' => 'BackDraft-BotUpdater/1.0']]);
    $data = @file_get_contents($url, false, $ctx);
    if ($data === false) { echo "  FAILED to download\n"; continue; }

    // Parse nginx map format: ~*pattern 1;
    preg_match_all('/~\*(\S+)\s+1;/', $data, $matches);
    foreach ($matches[1] as $pattern) {
        $pattern = trim($pattern);
        if (strlen($pattern) > 2 && strlen($pattern) < 200) {
            $external_bots[$pattern] = $name;
        }
    }
    echo "  Extracted " . count($matches[1]) . " patterns\n";
}

echo "Total external patterns: " . count($external_bots) . "\n\n";

// ── Insert/update external definitions in DB ─────────────────────────────
$upsert = $pdo->prepare("INSERT INTO backdraft_bot_definitions
    (name, pattern, match_type, classification, disposition, source, fingerprint_hash, auto_updated)
    VALUES (?, ?, 'contains', 'scanner', 'block', 'external', ?, 1)
    ON DUPLICATE KEY UPDATE source = 'external', auto_updated = 1, last_seen = NOW()");

$new_external = 0;
foreach ($external_bots as $pattern => $source) {
    $fingerprint = hash('sha256', strtolower($pattern));
    $name = ucfirst(str_replace(['~*', '\\', '.'], ['', '', ' '], $pattern));
    try {
        $upsert->execute([substr($name, 0, 128), $pattern, $fingerprint]);
        if ($pdo->lastInsertId()) $new_external++;
    } catch (PDOException $e) { /* duplicate, skip */ }
}
echo "New external definitions stored: {$new_external}\n";

// ── Generate nginx whitelist (good bots from DB) ─────────────────────────
// Only short identifier patterns (not full UA strings) — max 60 chars, no spaces in pattern
$good_bots = $pdo->query("SELECT pattern FROM backdraft_bot_definitions WHERE disposition = 'allow' AND active = 1 AND LENGTH(pattern) < 60 AND pattern NOT LIKE '% %' ORDER BY pattern")->fetchAll(PDO::FETCH_COLUMN);
// Also add hardcoded essentials
$whitelist_extra = [
    'Googlebot', 'Bingbot', 'Slurp', 'DuckDuckBot', 'Baiduspider', 'YandexBot',
    'facebot', 'facebookexternalhit', 'Twitterbot', 'LinkedInBot', 'Discordbot',
    'Slackbot', 'TelegramBot', 'WhatsApp', 'Applebot', 'PinterestBot',
    'UptimeRobot', 'Pingdom', 'StatusCake', 'Site24x7',
    'Feedbin', 'Feedly', 'FeedBurner', 'Inoreader',
    'Lighthouse', 'PageSpeed', 'GTmetrix', 'W3C_Validator',
];
$all_good = array_unique(array_merge($good_bots, $whitelist_extra));
sort($all_good);

$whitelist = "# Auto-generated by BackDraft — " . date('Y-m-d H:i:s') . "\n";
$whitelist .= "# " . count($all_good) . " good bots / crawlers\n";
foreach ($all_good as $bot) {
    if (strpos($bot, '~*') !== 0) $bot = "~*$bot";
    $whitelist .= "$bot 1;\n";
}

file_put_contents('/tmp/backdraft_bot_whitelist.conf', $whitelist);
exec('sudo cp /tmp/backdraft_bot_whitelist.conf /etc/nginx/whitelists/bot_whitelist.conf 2>&1', $o, $r);
unlink('/tmp/backdraft_bot_whitelist.conf');
echo "Whitelist written: " . count($all_good) . " entries (" . ($r === 0 ? "OK" : "FAILED") . ")\n";

// ── Generate nginx blacklist (bad bots from DB) ──────────────────────────
// Only short patterns for nginx map format — no full UA strings with spaces
$bad_bots = $pdo->query("SELECT DISTINCT pattern FROM backdraft_bot_definitions WHERE disposition = 'block' AND active = 1 AND LENGTH(pattern) < 60 AND pattern NOT LIKE '% %' ORDER BY pattern")->fetchAll(PDO::FETCH_COLUMN);

$blacklist = "# Auto-generated by BackDraft — " . date('Y-m-d H:i:s') . "\n";
$blacklist .= "# " . count($bad_bots) . " blocked bots\n";
foreach ($bad_bots as $bot) {
    if (strpos($bot, '~*') !== 0) $bot = "~*$bot";
    $blacklist .= "$bot 1;\n";
}

file_put_contents('/tmp/backdraft_bot_blacklist.conf', $blacklist);
exec('sudo cp /tmp/backdraft_bot_blacklist.conf /etc/nginx/blacklists/bot_blacklist.conf 2>&1', $o2, $r2);
unlink('/tmp/backdraft_bot_blacklist.conf');
echo "Blacklist written: " . count($bad_bots) . " entries (" . ($r2 === 0 ? "OK" : "FAILED") . ")\n";

// ── Test + reload nginx ──────────────────────────────────────────────────
exec('sudo nginx -t 2>&1', $test_out, $test_ret);
if ($test_ret === 0) {
    exec('sudo nginx -s reload 2>&1');
    echo "nginx reloaded\n";
} else {
    echo "nginx test FAILED\n" . implode("\n", $test_out) . "\n";
}

// ── Update config ────────────────────────────────────────────────────────
$pdo->prepare("INSERT INTO backdraft_config (config_key, config_value, description) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE config_value = VALUES(config_value)")
    ->execute(['bot_definitions_last_update', date('Y-m-d H:i:s'), 'Last external bot list download']);

// ── Summary ──────────────────────────────────────────────────────────────
$total = (int)$pdo->query("SELECT COUNT(*) FROM backdraft_bot_definitions WHERE active = 1")->fetchColumn();
$by_class = $pdo->query("SELECT classification, COUNT(*) as cnt FROM backdraft_bot_definitions WHERE active = 1 GROUP BY classification ORDER BY cnt DESC")->fetchAll();
echo "\n--- Bot Definition Summary ---\n";
echo "Total active definitions: {$total}\n";
foreach ($by_class as $c) echo "  {$c['classification']}: {$c['cnt']}\n";
echo "\nCompleted: " . date('Y-m-d H:i:s') . "\n";
